# Generated by Django 3.2.7 on 2021-09-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='callback_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='callback_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
