# Generated by Django 3.2.7 on 2021-09-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0004_auto_20210908_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
